swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
- "application/json"
produces:
- "application/json"

basePath: "/api"

paths:
  /te:
    post:
      operationId: "te_rest.post"
      tags:
      - "te"
      summary: "Send your text to NER processing"
      description: "Send a full sentence to the REST API"
      responses:
        200:
          description: "Successfully sent to the REST interface"
          schema:
            type: "string"
