swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
- application/json
produces:
- application/json

basePath: /api

paths:
  /te:
    post:
      operationId: te_rest.post
      tags:
      - text_enrichment
      summary: Send your text to NER processing
      description: Send a text to the REST API and start a NER processing.
      parameters:
        - name: text_enrichment
          in: body
          description: text to process
          schema:
            type: object
            properties:
              text:
                type: string
                description: Plain text to process
      responses:
        200:
          description: Successfully sent to the REST interface
          schema:
            type: string
